# Generated by Django 2.1 on 2019-03-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='pic_folder/default.jpg', upload_to='pic_folder/%Y%m%d'),
        ),
    ]
