# Generated by Django 2.1 on 2019-03-20 12:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('users', '0002_auto_20190319_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
