# Generated by Django 2.1 on 2019-03-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skill',
            new_name='skills',
        ),
    ]
