# Generated by Django 2.1 on 2019-03-13 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32)),
                ('file_size', models.CharField(max_length=10)),
                ('download_count', models.IntegerField(default=0)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2019, 3, 13, 12, 5, 14, 484795, tzinfo=utc))),
                ('file_path', models.CharField(max_length=32)),
                ('ip_addr', models.CharField(max_length=32)),
            ],
        ),
    ]
