# Generated by Django 2.1 on 2019-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/user.png', upload_to='pic_folder/%Y%m%d/'),
        ),
    ]
